Sanitizers (#101)
- Sanitizer builds
Add a configuration for sanitizers
Run TSan config, UBsan + ASan config
Ensure unit tests run with aligned configurations (and remove the CMake files)

- Various TSan fixes
Minor adjustments in memory orders

- Elf parser fixes
Fix to ignore some out of bound elf symbols
Addition of a test for the elf parser

- CI: Daily report of sanitizer issues

diff --git a/.github/workflows/test_workflow.yml b/.github/workflows/test_workflow.yml
--- a/.github/workflows/test_workflow.yml
+++ b/.github/workflows/test_workflow.yml
@@ -10,7 +10,7 @@ jobs:
   test-linux-glibc:
     strategy:
       matrix:
-        java_version: [ 8u362+9, 11.0.18+10, 17.0.6+10, 21.0.1+12 ]
+        java_version: [ 8u412+9, 11.0.23+12, 17.0.11+12, 21.0.3+12, 22.0.1+12 ]
         config: ${{ fromJson(inputs.configuration) }}
     runs-on: ubuntu-latest
     timeout-minutes: 180
@@ -21,6 +21,10 @@ jobs:
         with:
           distribution: 'temurin'
           java-version: "11"
+      - name: Setup OS
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y curl zip unzip libgtest-dev libgmock-dev
       - name: Prepare JDK ${{ matrix.java_version }}
         run: |
           wget -nv https://download.bell-sw.com/java/${{ matrix.java_version }}/bellsoft-jdk${{ matrix.java_version }}-linux-amd64.tar.gz -O jdk.tar.gz
@@ -28,11 +32,18 @@ jobs:
           find . -type d -name 'jdk*' -maxdepth 1| xargs -I {} mv {} test_jdk
       - name: Test
         run: |
+          sudo sysctl vm.mmap_rnd_bits=28
+
+          set +e
           export TEST_COMMIT=${{ github.sha }}
           export TEST_CONFIGURATION=glibc/${{ matrix.java_version }}
           export LIBC=glibc
           export JAVA_TEST_HOME=$(pwd)/test_jdk
-          ./gradlew :ddprof-test:test${{ matrix.config }} --info
+          ./gradlew :ddprof-test:test${{ matrix.config }}  
+          if [ $? -ne 0 ]; then 
+            echo "glibc-${{ matrix.java_version }}-${{ matrix.config }}" >> failures_glibc-${{ matrix.java_version }}-${{ matrix.config }}.txt
+            exit 1
+          fi
       - name: Upload logs
         uses: actions/upload-artifact@v3
         if: always()
@@ -48,13 +59,18 @@ jobs:
         with:
           name: x64-glibc-${{ matrix.java_version }}-${{ matrix.config }}
           path: build/
+      - uses: actions/upload-artifact@v3
+        if: failure()
+        with:
+          name: failures
+          path: failures_glibc-${{ matrix.java_version }}-${{ matrix.config }}.txt
 
   test-ubuntu-jdk:
     strategy:
       matrix:
-        java_version: [ 11, 17, 21 ]
+        java_version: [ '11.0.23-librca', '17.0.11-librca', '21.0.3-librca', '22.0.1-librca' ]
         config: ${{ fromJson(inputs.configuration) }}
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-latest
     timeout-minutes: 180
     steps:
       - uses: actions/checkout@v3
@@ -63,20 +79,32 @@ jobs:
         with:
           distribution: 'temurin'
           java-version: "11"
-      - name: Prepare JDK ${{ matrix.java_version }}
+      - name: Prepare OS
         run: |
           sudo apt-get update
-          sudo apt-get install openjdk-${{ matrix.java_version }}-jdk
-          uname -r
+          sudo apt-get install -y curl zip unzip libgtest-dev libgmock-dev
+      - name: Prepare JDK ${{ matrix.java_version }}
+        run: |
+          curl -s "https://get.sdkman.io" | bash
+          source "$HOME/.sdkman/bin/sdkman-init.sh"
+          echo 'n' | sdk install java ${{ matrix.java_version }}
       - name: Test
         run: |
+          sudo sysctl vm.mmap_rnd_bits=28
+          source "$HOME/.sdkman/bin/sdkman-init.sh"
+          
+          set +e
           export TEST_COMMIT=${{ github.sha }}
           export TEST_CONFIGURATION=glibc/${{ matrix.java_version }}
           export LIBC=glibc
-          export JAVA_TEST_HOME=/usr/lib/jvm/java-${{ matrix.java_version }}-openjdk-amd64
+          export JAVA_TEST_HOME=${SDKMAN_DIR}/candidates/java/${{ matrix.java_version }}
           export JAVA_HOME=$JAVA_HOME
           export PATH=$JAVA_HOME/bin:$PATH
-          ./gradlew :ddprof-test:test${{ matrix.config }} --info
+          ./gradlew :ddprof-test:test${{ matrix.config }}
+          if [ $? -ne 0 ]; then 
+            echo "ubuntu-jdk-${{ matrix.java_version }}-${{ matrix.config }}" >> failures_ubuntu-jdk-${{ matrix.java_version }}-${{ matrix.config }}.txt
+            exit 1
+          fi
       - name: Upload logs
         uses: actions/upload-artifact@v3
         if: always()
@@ -92,6 +120,11 @@ jobs:
         with:
           name: x64-ubuntu-jdk-${{ matrix.java_version }}-${{ matrix.config }}
           path: build/
+      - uses: actions/upload-artifact@v3
+        if: failure()
+        with:
+          name: failures
+          path: failures_ubuntu-jdk-${{ matrix.java_version }}-${{ matrix.config }}.txt
 
   test-linux-glibc-j9:
     strategy:
@@ -102,6 +135,11 @@ jobs:
     timeout-minutes: 180
     steps:
       - uses: actions/checkout@v3
+      - name: Setup OS
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y curl zip unzip libgtest-dev libgmock-dev
+#          sudo sysctl vm.mmap_rnd_bits=28
       - name: Prepare test JDK
         uses: actions/setup-java@v3
         with:
@@ -116,11 +154,16 @@ jobs:
           java-version: "11"
       - name: Test
         run: |
+          set +e
           export TEST_COMMIT=${{ github.sha }}
           export TEST_CONFIGURATION=glibc/${{ matrix.java_version }}
           export LIBC=glibc
           chmod a+x gradlew
-          ./gradlew :ddprof-test:test${{ matrix.config }} --info
+          ./gradlew :ddprof-test:test${{ matrix.config }}
+          if [ $? -ne 0 ]; then 
+            echo "glibc-j9-${{ matrix.java_version }}-${{ matrix.config }}" >> failures_glibc-j9-${{ matrix.java_version }}-${{ matrix.config }}.txt
+            exit 1
+          fi
       - name: Upload logs
         uses: actions/upload-artifact@v3
         if: always()
@@ -136,15 +179,24 @@ jobs:
         with:
           name: x64-glibc-j9-${{ matrix.java_version }}-${{ matrix.config }}
           path: build/
+      - uses: actions/upload-artifact@v3
+        if: failure()
+        with:
+          name: failures
+          path: failures_glibc-j9-${{ matrix.java_version }}-${{ matrix.config }}.txt
 
   test-linux-glibc-oracle8:
     strategy:
       matrix:
         config: ${{ fromJson(inputs.configuration) }}
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-latest
     timeout-minutes: 180
     steps:
       - uses: actions/checkout@v3
+      - name: Setup OS
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y curl zip unzip libgtest-dev libgmock-dev
       - name: Prepare build JDK
         uses: actions/setup-java@v3
         with:
@@ -152,7 +204,7 @@ jobs:
           java-version: "11"
       - name: Prepare JDK ${{ matrix.java_version }}
         run: |
-          sudo apt-get -y update && sudo apt-get -y install curl
+          sudo sysctl vm.mmap_rnd_bits=28
           set -eux;
           sudo mkdir -p /usr/lib/jvm/oracle8;
           # https://gist.github.com/wavezhang/ba8425f24a968ec9b2a8619d7c2d86a6?permalink_comment_id=4444663#gistcomment-4444663
@@ -161,13 +213,18 @@ jobs:
           uname -r
       - name: Test
         run: |
+          set +e
           export TEST_COMMIT=${{ github.sha }}
           export TEST_CONFIGURATION=glibc/8
           export LIBC=glibc
           export JAVA_TEST_HOME=/usr/lib/jvm/oracle8
           export JAVA_HOME=$JAVA_HOME
           export PATH=$JAVA_HOME/bin:$PATH
-          ./gradlew :ddprof-test:test${{ matrix.config }} --info
+          ./gradlew :ddprof-test:test${{ matrix.config }}
+          if [ $? -ne 0 ]; then 
+            echo "glibc-oracle8-${{ matrix.config }}" >> failures_glibc-oracle8-${{ matrix.config }}.txt
+            exit 1
+          fi
       - name: Upload logs
         uses: actions/upload-artifact@v3
         if: always()
@@ -183,11 +240,16 @@ jobs:
         with:
           name: x64-oracle-jdk8-${{ matrix.config }}
           path: build/
+      - uses: actions/upload-artifact@v3
+        if: failure()
+        with:
+          name: failures
+          path: failures_glibc-oracle8-${{ matrix.config }}.txt
 
   test-linux-musl:
     strategy:
       matrix:
-        java_version: [ 8u362+9, 11.0.18+10, 17.0.6+10, 21.0.1+12 ]
+        java_version: [ 8u412+9, 11.0.23+12, 17.0.11+12, 21.0.3+12, 22.0.1+12 ]
         config: ${{ fromJson(inputs.configuration) }}
     runs-on: ubuntu-latest
     timeout-minutes: 180
@@ -197,8 +259,8 @@ jobs:
       options: --cpus 2
     steps:
       - uses: actions/checkout@v3
-      - name: Setup system
-        run: apk update && apk add curl moreutils wget hexdump linux-headers bash make g++ clang git cppcheck jq cmake >/dev/null
+      - name: Setup OS
+        run: apk update && apk add curl moreutils wget hexdump linux-headers bash make g++ clang git cppcheck jq cmake gtest-dev gmock >/dev/null
       - name: Prepare build JDK
         run: |
           wget -nv https://download.bell-sw.com/java/11.0.18+10/bellsoft-jdk11.0.18+10-linux-x64-musl.tar.gz -O jdk.tar.gz
@@ -211,14 +273,18 @@ jobs:
           find . -type d -name 'jdk*' -maxdepth 1 | xargs -I {} mv {} test_jdk
       - name: Test
         run: |
-          set -x
+          set +e
           export JAVA_HOME=$(pwd)/build_jdk
           export PATH=$JAVA_HOME/bin:$PATH
           export TEST_COMMIT=${{ github.sha }}
           export TEST_CONFIGURATION=musl/${{ matrix.java_version }}
           export LIBC=musl
           export JAVA_TEST_HOME=$(pwd)/test_jdk 
-          ./gradlew :ddprof-test:test${{ matrix.config }} --info
+          ./gradlew :ddprof-test:test${{ matrix.config }}
+          if [ $? -ne 0 ]; then 
+            echo "musl-${{ matrix.java_version }}-${{ matrix.config }}" >> failures_musl-${{ matrix.java_version }}-${{ matrix.config }}.txt
+            exit 1
+          fi
       - name: Upload logs
         uses: actions/upload-artifact@v3
         if: always()
@@ -234,6 +300,11 @@ jobs:
         with:
           name: x64-musl-${{ matrix.java_version }}-${{ matrix.config }}
           path: build/
+      - uses: actions/upload-artifact@v3
+        if: failure()
+        with:
+          name: failures
+          path: failures_musl-${{ matrix.java_version }}-${{ matrix.config }}.txt
 
   test-linux-glibc-zing:
     strategy:
@@ -244,13 +315,23 @@ jobs:
     timeout-minutes: 180
 
     steps:
+      - name: Set config output
+        id: set_config
+        run: echo "::set-output name=config::${{ matrix.config }}"
       - uses: actions/checkout@v3
+        if: steps.set_config.outputs.config == 'release' || steps.set_config.outputs.config == 'debug'
+      - name: Setup OS
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y curl zip unzip libgtest-dev libgmock-dev
       - name: Prepare build JDK
+        if: steps.set_config.outputs.config == 'release' || steps.set_config.outputs.config == 'debug'
         uses: actions/setup-java@v3
         with:
           distribution: 'temurin'
           java-version: "11"
       - name: Prepare JDK ${{ matrix.java_version }}
+        if: steps.set_config.outputs.config == 'release' || steps.set_config.outputs.config == 'debug'
         run: |
           sudo apt-get -y update && sudo apt-get -y install curl g++-9 gcc-9
           sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100 --slave /usr/bin/g++ g++ /usr/bin/g++-9
@@ -273,14 +354,20 @@ jobs:
           # rename the bundled libstdc++.so to avoid conflicts with the system one
           sudo mv /usr/lib/jvm/zing/etc/libc++/libstdc++.so.6 /usr/lib/jvm/zing/etc/libc++/libstdc++.so.6.bak
       - name: Test
+        if: steps.set_config.outputs.config == 'release' || steps.set_config.outputs.config == 'debug'
         run: |
+          set +e
           export TEST_COMMIT=${{ github.sha }}
           export TEST_CONFIGURATION=glibc/${{ matrix.java_version }}
           export LIBC=glibc
           export JAVA_TEST_HOME=/usr/lib/jvm/zing
           export JAVA_HOME=$JAVA_HOME
           export PATH=$JAVA_HOME/bin:$PATH
-          ./gradlew :ddprof-test:test${{ matrix.config }} --info
+          ./gradlew :ddprof-test:test${{ matrix.config }}
+          if [ $? -ne 0 ]; then 
+            echo "glibc-zing-${{ matrix.java_version }}-${{ matrix.config }}" >> failures_zing-${{ matrix.java_version }}-${{ matrix.config }}.txt
+            exit 1
+          fi
       - name: Upload logs
         uses: actions/upload-artifact@v3
         if: always()
@@ -296,3 +383,8 @@ jobs:
         with:
           name: x64-glibc-zing-${{ matrix.java_version }}-${{ matrix.config }}
           path: build/
+      - uses: actions/upload-artifact@v3
+        if: failure()
+        with:
+          name: failures
+          path: failures_zing-${{ matrix.java_version }}-${{ matrix.config }}.txt
